include("matrices_de_costo.jl")
include("algoritmo_greedy_random.jl")
include("busquedaLocal.jl")

function grasp(secuencias, limiteIteracionesSinMejora, cantidadIteracionesMaximas, cantMejorasBusquedaLocal)
    matriz = matrizDeAminoacidos()
    iteracionesSinMejora = 0
    iteracion = 0

    println("///////////ARRANCO A CORRER GRASP///////////")

    mejorScore = 0
    mejorResultado = nothing

    while (iteracionesSinMejora < limiteIteracionesSinMejora && iteracion < cantidadIteracionesMaximas)
        println("///////////ARRANCO ITERACION NUMERO: ", iteracion, " ///////////")
        secuenciasAux = copy(secuencias)

        corridaRandom = algoritmoGreedyRandom(secuenciasAux, matriz, 1.5)
        resultadoBusquedaLocal = busquedaLocal(corridaRandom, cantMejorasBusquedaLocal, matriz)

        if(resultadoBusquedaLocal.score > mejorScore)
            #Hubo una mejora
            println("hubo una mejora, el nuevo score es: ", resultadoBusquedaLocal.score)
            mejorScore = resultadoBusquedaLocal.score
            mejorResultado = resultadoBusquedaLocal
            iteracionesSinMejora = 0

        else
            println("NO hubo mejora")
            #Queda una iteracion menos
            iteracionesSinMejora += 1
        end

        iteracion += 1
        println(mejorScore)
    end

    return mejorResultado
end

grasp([
Cadena("LCQGTSNKLTQLGTFEDHFLSLRRMFNNCEVVLGNLEITYVQKNYDLSFLKTIQEVAGYVLIALNTVERIPLENLQIIRGNMYYENSYALAVLSNYGTNKSGLRELPMRSLQEVL"),
Cadena("VCQGTSNRLTQLGTFEDHFLSLQRMFNNCEVVLGNLEITYMQRNYDLSFLKTIQEVAGYVLIALNTVEKIPLENLQIIRGNVLYENTHALSVLSNYGSNKTGLQELPLRNLHEIL"),
Cadena("IILVQICQGTSNRLTQLGTFEDHFLSLQRMFNNCEVVLGNLEITYMQKNYDLSFLKTIQEVAGYVLIALNTVEKIPLENLQIIRGNVLYENTHALSVLSNYGANKVGLRELPMRNLQEIL"),
Cadena("FCQGTSNKLTQLGTFEDHFLSLQRMFNNCEVVLGNLEITYVQRNYDLSFLKTIQEVAGYVLIALNTVERIPLENLQIIRGNLLYENTYALAVLSNYGANKTGVKELPMRNLQEIL"),
Cadena("VCQGTSNKLTQLGTFEDHFLSLQRMFNNCEVVLGNLEITYVQRNYDLSFLKTIQEVAGYVLIALNTVERIPLENLQIIRGNMYYENSYALAVLSNYDANKTGLKELPMRNLQEIL"),
Cadena("LEEKKVCQGTSNKLTQLGTFEDHFLSLQRMFNNCEVVLGNLEITYVQRNYDLSFLKTIQEVAGYVLIALNTVERIPLENLQIIRGNMYYENSYALAVLSNYDANKTGLKELPMRNLQEIL"),
Cadena("MFNNCEVVLGNLEITYVQRNYDLSFLKTIQEVAGYVLIALNTVERIPLENLQIIRGNMYYENSYALAVLSNYDANKTGLKELPMRNLQEIL"),
Cadena("LEEKKVCQGTSNKLTQLGTFEDHFLSLQRMFNNCEVVLGNLEITYVQRNYDLSFLKTIQEVAGYVLIALNTVERIPLENLQIIRGNMYYENSYALAVLSNYDANKTGLKELPMRNLQEIL"),
Cadena("MFNNCEVVLGNLEITYVQRNYDLSFLKTIQEVAGYVLIALNTVERIPLENLQIIRGNMYYENSYALAVLSNYDANKTGLKELPMRNLQEIL"),
Cadena("LEEKKVCQGTSNKLTQLGTFEDHFLSLQRMFNNCEVVLGNLEITYVQRNYDLSFLKTIQEVAGYVLIALNTVERIPLENLQIIRGNMYYENSYALAVLSNYDANKTGLKELPMRNLQEIL"),
Cadena("FLPSLVCQGTSNKLTQLGTFEDHFVSLQRMFNNCEVVLGNLEITYVQKNYDLSFLKTIQEVAGYVLIALNAVEKIPLENLQVIRGNVLYENFYALSVLSNYDVNKTGVKELPMRNLLEIL"),
Cadena("LASGICQGTGNKLTQLGTLDDHFLSLQRMYNNCEVVLGNLEITYVQRNYDLSFLKTIQEVAGYVLIALNSVETIPLVNLQIIRGNVLYEGFALAVLSNYGMNKTGLKELPMRNLLEIL")],
10,
20,
10
)
